Repository th-ch/youtube-music, pull requests merged in 2023-10, with the labels that each got.

#1264 feat(GitHub): add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#1257 Bump version to 2.0.0
  package-lock.json
  package.json
Labels: release

#1271 hotfix(last-fm): fix last-fm plugin
  plugins/last-fm/back.ts
Labels: bug

#1276 Fix in-app-menu squishing sub-menu items
  plugins/in-app-menu/menu/panel.ts
  plugins/in-app-menu/titlebar.css
Labels: bug

#1277 hotfix: fixed app launching offscreen
  index.ts
Labels: bug

#1278 fix: discord-rpc
  plugins/discord/back.ts
Labels: bug

#1280 hotfix: revert "Fix for windows zoom (ScaleFactor)"
  index.ts
Labels: bug

#1279 feat: fallback to DOM window controls on platforms without native support
  plugins/discord/back.ts
  plugins/in-app-menu/assets/close.svg
  plugins/in-app-menu/assets/maximize.svg
  plugins/in-app-menu/assets/menu.svg
  plugins/in-app-menu/assets/minimize.svg
  plugins/in-app-menu/assets/unmaximize.svg
  plugins/in-app-menu/back.ts
  plugins/in-app-menu/front.ts
  plugins/in-app-menu/titlebar.css
Labels: enhancement

#1272 feat: use nsis-web instead of nsis
  package.json
  readme.md
Labels: enhancement

#1283 fix: fix missing icons in taskbar-mediacontrol
  plugins/notifications/interactive.ts
  plugins/notifications/utils.ts
  plugins/taskbar-mediacontrol/back.ts
  plugins/utils.ts
Labels: bug

#1286 Fix: typo in README
  readme.md
Labels: typo

#1291 fix(mpris): fixed an issue where MPRIS information was incorrect
  package-lock.json
  package.json
  plugins/shortcuts/mpris-service.d.ts
  plugins/shortcuts/mpris.ts
  providers/song-info-front.ts
Labels: bug

#1292 feat(deps): bundle `youtubei.js` (temporary solution)
  package-lock.json
  package.json
  patches/youtubei.js+6.4.1.patch
  rollup.main.config.ts
Labels: enhancement

#1293 feat(discord): add `Hide GitHub link Button`
  config/defaults.ts
  plugins/discord/menu.ts
Labels: enhancement

#1296 Fix Library removed for Premium users
  preload.ts
Labels: bug

#1301 hotfix(adblocker): fix `ipcRenderer.sendSync() with ...`
  index.ts
  plugins/adblocker/back.ts
  plugins/adblocker/blocker.ts
  plugins/adblocker/config.ts
Labels: bug

#1304 fix: fixed an issue that caused inconsistent execution results
  config/defaults.ts
  index.ts
  menu.ts
  package-lock.json
  package.json
  plugins/adblocker/inject-cliqz-preload.ts
  plugins/adblocker/preload.ts
  plugins/bypass-age-restrictions/front.ts
  plugins/bypass-age-restrictions/simple-youtube-age-restriction-bypass.d.ts
  plugins/visualizer/butterchurn.d.ts
  plugins/visualizer/visualizers/butterchurn.ts
  utils/generate-package-json.js
Labels: bug, dependencies

#1311 feat(in-app-menu): enable in-app-menu by default (in Windows)
  config/defaults.ts
  config/store.ts
  plugins/in-app-menu/back.ts
  plugins/in-app-menu/front.ts
Labels: enhancement

#1310 feat(downloader): Added support for audio format auto-detection
  config/defaults.ts
  config/store.ts
  plugins/downloader/back.ts
  plugins/downloader/menu.ts
  plugins/downloader/types.ts
  plugins/downloader/utils.ts
Labels: enhancement

#1317 Fix mpris `player.loopStatus`
  plugins/shortcuts/mpris.ts
Labels: bug

#1316 feat: migrate from `npm` to `pnpm`
  .github/workflows/build.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  readme.md
Labels: enhancement

#1326 Added missing plugins in ReadMe
  readme.md
Labels: documentation

#1329 fix: fixed an issue where only the first 100 songs in a playlist were downloaded
  src/plugins/downloader/back.ts
Labels: bug

#1331 chore(deps): update dependency electron to v27.0.1
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1334 fix: fixed an issue where the album name was missing
  src/providers/song-info-front.ts
  src/types/player-api-events.ts
Labels: bug

#1335 feat(in-app-menu): add an option to hide the window controls
  src/config/defaults.ts
  src/menu.ts
  src/plugins/in-app-menu/front.ts
  src/plugins/in-app-menu/menu.ts
Labels: enhancement

#1342 fix: fixed bugs in downloader
  src/config/plugins.ts
  src/plugins/downloader/back.ts
Labels: bug

#1349 feat(ambient-mode): add config for `ambient-mode` plugin
  src/config/defaults.ts
  src/menu.ts
  src/plugins/ambient-mode/back.ts
  src/plugins/ambient-mode/config.ts
  src/plugins/ambient-mode/front.ts
  src/plugins/ambient-mode/menu.ts
  src/plugins/ambient-mode/style.css
Labels: bug, enhancement
