Repository th-ch/youtube-music, pull requests merged in 2024-12, with the labels that each got.

#2659 Fixed #2514
  src/youtube-music.css
Labels: bug

#2676 fix(album-actions): Fixed #2312, #2502
  src/plugins/album-actions/index.ts
Labels: bug

#2708 fix: Laggy scrolling behaviour in large playlists
  src/plugins/in-app-menu/titlebar.css
Labels: bug

#2714 fix: discord rich presence connection status
  src/plugins/discord/main.ts
Labels: bug

#2713 fix: tab misalignment
  src/plugins/blur-nav-bar/style.css
Labels: bug

#2736 Fixed #1796
  src/youtube-music.css
Labels: bug

#2575 feat: Add equalizer plugin with presets (e.g. bass booster)
  README.md
  src/i18n/resources/en.json
  src/plugins/equalizer/index.ts
  src/plugins/equalizer/presets.ts
Labels: enhancement

#2666 fix(discord): Fix Album Art failing on Discord RPC
  src/providers/song-info.ts
Labels: bug

#2754 fix: Add Flatpak permissions needed for MPRIS and tray icon
  package.json
Labels: bug

#2755 feat: Specify flatpak runtime
  package.json
Labels: enhancement

#2758 fix: Set correct window class for X11 and Wayland
  package.json
  src/index.ts
Labels: bug

#2383 feat(synced-lyrics): multiple lyric sources
  package.json
  src/i18n/resources/en.json
  src/index.ts
  src/plugins/lyrics-genius/types.ts
  src/plugins/synced-lyrics/index.ts
  src/plugins/synced-lyrics/menu.ts
  src/plugins/synced-lyrics/parsers/lrc.ts
  src/plugins/synced-lyrics/providers/LRCLib.ts
  src/plugins/synced-lyrics/providers/LyricsGenius.ts
  src/plugins/synced-lyrics/providers/Megalobiz.ts
  src/plugins/synced-lyrics/providers/MusixMatch.ts
  src/plugins/synced-lyrics/providers/YTMusic.ts
  src/plugins/synced-lyrics/providers/index.ts
  src/plugins/synced-lyrics/renderer/components/ErrorDisplay.tsx
  src/plugins/synced-lyrics/renderer/components/LoadingKaomoji.tsx
  src/plugins/synced-lyrics/renderer/components/LyricsContainer.tsx
  src/plugins/synced-lyrics/renderer/components/LyricsPicker.tsx
  src/plugins/synced-lyrics/renderer/components/PlainLyrics.tsx
  src/plugins/synced-lyrics/renderer/components/SyncedLine.tsx
  src/plugins/synced-lyrics/renderer/index.ts
  src/plugins/synced-lyrics/renderer/lyrics/fetch.ts
  src/plugins/synced-lyrics/renderer/lyrics/index.ts
  src/plugins/synced-lyrics/renderer/renderer.tsx
  src/plugins/synced-lyrics/renderer/utils.tsx
  src/plugins/synced-lyrics/style.css
  src/plugins/synced-lyrics/types.ts
  src/types/icons.ts
  src/yt-web-components.d.ts
Labels: enhancement

#2554 feat(synced-lyrics): Better-Lyrics Styling for Synced-Lyrics
  src/i18n/resources/en.json
  src/plugins/synced-lyrics/index.ts
  src/plugins/synced-lyrics/menu.ts
  src/plugins/synced-lyrics/renderer/components/SyncedLine.tsx
  src/plugins/synced-lyrics/renderer/renderer.tsx
  src/plugins/synced-lyrics/style.css
  src/plugins/synced-lyrics/types.ts
Labels: enhancement

#2630 feat(api-server): Add repeat mode and seek time API
  src/plugins/api-server/backend/main.ts
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/api-server/backend/types.ts
Labels: enhancement

#2748 feat(api-server): add absolute seek endpoint
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/api-server/backend/scheme/index.ts
  src/plugins/api-server/backend/scheme/seek.ts
  src/providers/song-controls.ts
Labels: enhancement

#2723 feat(amuse): song query api (add amuse plugin)
  src/i18n/resources/en.json
  src/plugins/amuse/backend.ts
  src/plugins/amuse/index.ts
  src/plugins/amuse/types.ts
Labels: enhancement

#2767 feat(api-server): Add queue api
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/api-server/backend/scheme/index.ts
  src/plugins/api-server/backend/scheme/queue.ts
  src/plugins/api-server/backend/scheme/search.ts
  src/providers/song-controls.ts
  src/renderer.ts
  src/types/queue.ts
Labels: enhancement

#2788 fix(synced-lyrics): Revert font-size behavior for non-fancy modes
  src/plugins/synced-lyrics/renderer/renderer.tsx
  src/plugins/synced-lyrics/style.css
Labels: bug

#2783 Refactor Menu Navigation and Update Media Control Icons
  assets/media-icons-black/next.png
  assets/media-icons-black/pause.png
  assets/media-icons-black/play.png
  assets/media-icons-black/previous.png
  src/menu.ts
Labels: bug, enhancement

#2791 fix: update event handler from onVolumeTap to onVolumeClick
  src/renderer.ts
Labels: bug
