Repository th-ch/youtube-music, pull requests merged in 2024-01, with the labels that each got.

#1637 fix(#1543): fix song control doesn't work
  src/providers/song-controls.ts
  src/renderer.ts
Labels: bug

#1624 chore(README): Fix plugins names and add plugins in/to Readme (in menu too)
  README.md
  src/i18n/resources/en.json
Labels: documentation

#1640 feat: Better Scrobbler Plugin
  src/config/store.ts
  src/i18n/resources/cs.json
  src/i18n/resources/de.json
  src/i18n/resources/el.json
  src/i18n/resources/en.json
  src/i18n/resources/es.json
  src/i18n/resources/fr.json
  src/i18n/resources/it.json
  src/i18n/resources/ja.json
  src/i18n/resources/ko.json
  src/i18n/resources/lt.json
  src/i18n/resources/nb.json
  src/i18n/resources/pl.json
  src/i18n/resources/pt.json
  src/i18n/resources/ru.json
  src/i18n/resources/tr.json
  src/i18n/resources/uk.json
  src/i18n/resources/zh-CN.json
  src/i18n/resources/zh-TW.json
  src/plugins/last-fm/index.ts
  src/plugins/last-fm/main.ts
  src/plugins/scrobbler/index.ts
  src/plugins/scrobbler/main.ts
  src/plugins/scrobbler/menu.ts
  src/plugins/scrobbler/services/base.ts
  src/plugins/scrobbler/services/lastfm.ts
  src/plugins/scrobbler/services/listenbrainz.ts
Labels: enhancement

#1665 Support disabling scrobbling for non-music content
  README.md
  src/config/defaults.ts
  src/i18n/resources/en.json
  src/plugins/scrobbler/index.ts
  src/plugins/scrobbler/main.ts
  src/plugins/scrobbler/menu.ts
  src/providers/song-info-front.ts
  src/providers/song-info.ts
Labels: enhancement
