Repository th-ch/youtube-music, pull requests merged in 2024-03, with the labels that each got.

#1818 Revert "chore(deps): update dependency electron-builder to v24.13.3"
  package.json
  pnpm-lock.yaml
Labels: bug

#1853 Improve ambient mode
  src/plugins/ambient-mode/index.ts
  src/plugins/ambient-mode/style.css
Labels: enhancement

#1833 chore(README): Nicer Readme 2.0
  README.md
  docs/readme/README-is.md
  docs/readme/README-ko.md
Labels: documentation

#1862 fix(style): fixed image/video alignment when toggle is active
  src/youtube-music.css
Labels: bug

#1863 fix: Fix Miniplayer image size
  src/plugins/ambient-mode/style.css
Labels: bug

#1880 Ambient Plugin cleanup
  src/plugins/ambient-mode/index.ts
  src/plugins/ambient-mode/menu.ts
  src/plugins/ambient-mode/types.ts
Labels: bug

#1667 Improve video title filters
  src/providers/song-info.ts
Labels: enhancement
