Repository th-ch/youtube-music, pull requests merged in 2024-05, with the labels that each got.

#2049 readme file translated to french
  docs/readme/README-fr.md
Labels: documentation

#2004 chore (README-is.md): Replace viðbót with tengiforrit
  docs/readme/README-is.md
Labels: documentation

#2033 Enable arm64 for deb and rpm
  README.md
  package.json
Labels: enhancement

#1996 Prevents player to start with invalid MPRIS interface
  src/plugins/shortcuts/main.ts
Labels: bug
