Repository th-ch/youtube-music, pull requests merged in 2024-02, with the labels that each got.

#1685 feat(album-color-theme): support album color theme in all pages
  src/i18n/resources/en.json
  src/plugins/album-color-theme/index.ts
  src/plugins/album-color-theme/style.css
  src/plugins/blur-nav-bar/style.css
  src/plugins/in-app-menu/titlebar.css
Labels: enhancement

#1710 refactor(in-app-menu): refactor `in-app-menu` plugin
  electron.vite.config.mts
  package.json
  pnpm-lock.yaml
  src/plugins/in-app-menu/assets/close.svg
  src/plugins/in-app-menu/assets/maximize.svg
  src/plugins/in-app-menu/assets/menu.svg
  src/plugins/in-app-menu/assets/minimize.svg
  src/plugins/in-app-menu/assets/unmaximize.svg
  src/plugins/in-app-menu/constants.ts
  src/plugins/in-app-menu/index.ts
  src/plugins/in-app-menu/main.ts
  src/plugins/in-app-menu/menu/icons.ts
  src/plugins/in-app-menu/menu/panel.ts
  src/plugins/in-app-menu/renderer.ts
  src/plugins/in-app-menu/renderer.tsx
  src/plugins/in-app-menu/renderer/IconButton.tsx
  src/plugins/in-app-menu/renderer/MenuButton.tsx
  src/plugins/in-app-menu/renderer/Panel.tsx
  src/plugins/in-app-menu/renderer/PanelItem.tsx
  src/plugins/in-app-menu/renderer/TitleBar.tsx
  src/plugins/in-app-menu/renderer/WindowController.tsx
  src/plugins/in-app-menu/titlebar.css
  tsconfig.json
Labels: enhancement

#1758 feat(scrobblers): use `BrowserWindow` instead of `shell.openExternal`
  src/i18n/resources/en.json
  src/plugins/scrobbler/main.ts
  src/plugins/scrobbler/menu.ts
  src/plugins/scrobbler/services/base.ts
  src/plugins/scrobbler/services/lastfm.ts
  src/plugins/scrobbler/services/listenbrainz.ts
Labels: enhancement

#1769 [MPRIS] Issue Fixes and additional properties support
  src/index.ts
  src/plugins/music-together/index.ts
  src/plugins/music-together/queue/queue.ts
  src/plugins/music-together/types.ts
  src/plugins/notifications/interactive.ts
  src/plugins/shortcuts/mpris-service.d.ts
  src/plugins/shortcuts/mpris.ts
  src/providers/protocol-handler.ts
  src/providers/song-controls.ts
  src/providers/song-info-front.ts
  src/providers/song-info.ts
  src/renderer.ts
  src/types/datahost-get-state.ts
  src/types/queue.ts
  src/types/youtube-music-desktop-internal.ts
Labels: enhancement

#1760 fix: fix bugs in MPRIS, and improve MPRIS
  src/index.ts
  src/plugins/music-together/index.ts
  src/plugins/music-together/queue/queue.ts
  src/plugins/music-together/types.ts
  src/plugins/notifications/interactive.ts
  src/plugins/shortcuts/mpris-service.d.ts
  src/plugins/shortcuts/mpris.ts
  src/providers/protocol-handler.ts
  src/providers/song-controls.ts
  src/providers/song-info-front.ts
  src/providers/song-info.ts
  src/renderer.ts
  src/types/datahost-get-state.ts
  src/types/queue.ts
  src/types/youtube-music-desktop-internal.ts
Labels: bug

#1786 fix: center the pause icon
  assets/youtube-music-tray-paused.png
Labels: enhancement

#1806 Icelandic translation of the readme file
  README.md
  docs/readme/README-is.md
Labels: documentation
