Repository th-ch/youtube-music, pull requests merged in 2025-04, with the labels that each got.

#3180 docs: add Japanese README
  README.md
  docs/readme/README-es.md
  docs/readme/README-fr.md
  docs/readme/README-hu.md
  docs/readme/README-is.md
  docs/readme/README-ja.md
  docs/readme/README-ko.md
Labels: documentation

#3174 Fix custom Video/Audio switcher in Plugins menu
  src/plugins/video-toggle/index.ts
Labels: enhancement

#3192 docs: add Portuguese README translation and update language shortcuts
  README.md
  docs/readme/README-es.md
  docs/readme/README-fr.md
  docs/readme/README-hu.md
  docs/readme/README-is.md
  docs/readme/README-ko.md
  docs/readme/README-pt.md
  docs/readme/README-ru.md
Labels: documentation

#3226 fix(mpris): keep MPRIS volume in sync with the actual volume
  src/plugins/shortcuts/mpris.ts
Labels: bug

#3206 Synced Lyrics: Also search for lyrics with the original title language
  src/plugins/synced-lyrics/providers/LRCLib.ts
  src/plugins/synced-lyrics/types.ts
  src/providers/song-info.ts
Labels: enhancement

#3247 fix(unobtrusive-player): handle shuffle play
  src/plugins/unobtrusive-player/index.ts
Labels: bug

#3277 fix cuted "j" and glow in lyrics
  src/plugins/synced-lyrics/style.css
Labels: enhancement

#3288 feat(tuna-obs): added alternativeTitle and tags to tuna
  src/plugins/tuna-obs/index.ts
Labels: enhancement
