Repository th-ch/youtube-music, pull requests merged in 2025-05, with the labels that each got.

#3306 fix(album-actions): use playlist shelf for playlist detection
  src/plugins/album-actions/index.ts
Labels: bug

#3338 Docs: Add Ukrainian translation
  README.md
  docs/readme/README-es.md
  docs/readme/README-fr.md
  docs/readme/README-hu.md
  docs/readme/README-is.md
  docs/readme/README-ja.md
  docs/readme/README-ko.md
  docs/readme/README-pt.md
  docs/readme/README-ru.md
  docs/readme/README-uk.md
Labels: documentation

#3175 feat(plugin): support authenticated proxy
  package.json
  pnpm-lock.yaml
  src/i18n/resources/en.json
  src/i18n/resources/zh-CN.json
  src/index.ts
  src/plugins/auth-proxy-adapter/backend/index.ts
  src/plugins/auth-proxy-adapter/backend/types.ts
  src/plugins/auth-proxy-adapter/config.ts
  src/plugins/auth-proxy-adapter/index.ts
  src/plugins/auth-proxy-adapter/menu.ts
Labels: enhancement

#3362 fix(precise-volume): replace constructor check for volume slider
  src/plugins/precise-volume/renderer.ts
Labels: bug
