Repository th-ch/youtube-music, pull requests merged in 2025-02, with the labels that each got.

#2940 Fix reverse direction of synced lyrics for persian or other rtl languages
  src/plugins/synced-lyrics/renderer/components/SyncedLine.tsx
Labels: bug

#2963 fix: remove disable-gpu-memory-buffer-video-frames flag
  src/index.ts
Labels: enhancement

#2981 fix(vite): set server.cors.origin
  electron.vite.config.mts
Labels: bug

#2987 fix(downloader): use the upgrade button to check for premium status
  src/plugins/downloader/main/index.ts
Labels: bug

#2990 fix(plugin-loader): update context filtering logic for backend mode
  vite-plugins/plugin-loader.mts
Labels: bug

#2995 fix: Match engines.pnpm with the pnpm version used to create the lock files
  package.json
Labels: bug

#3015 fix(deps): update dependency youtubei.js to v13.1.0
  package.json
  pnpm-lock.yaml
Labels: dependencies

#3022 fix: Filter for only `MusicResponsiveListItem` in playlist items
  src/plugins/downloader/main/index.ts
Labels: bug

#3025 fix: Updated tray pause icon for consistency
  assets/youtube-music-tray-paused.png
Labels: enhancement

#3010 fix(no-google-login): Remove Library icon removal code
  src/plugins/no-google-login/index.ts
Labels: enhancement
