Repository th-ch/youtube-music, pull requests merged in 2025-01, with the labels that each got.

#2808 feat(api-server): add `insertPosition` for `addSongToQueue`
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/api-server/backend/scheme/queue.ts
  src/providers/song-controls.ts
  src/renderer.ts
Labels: enhancement

#2843 Create Transalated README-hu.md
  docs/readme/README-hu.md
Labels: documentation

#2844 Create Transalated youtube-music-hu.svg
  web/youtube-music-hu.svg
Labels: documentation

#2847 Fixing the Content section in the README-ru.md file.
  docs/readme/README-ru.md
Labels: documentation

#2792 feat(api-server): add endpoint to get shuffle state
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/shortcuts/mpris-service.d.ts
  src/plugins/shortcuts/mpris.ts
  src/providers/song-controls.ts
  src/providers/song-info-front.ts
  src/renderer.ts
Labels: enhancement

#2905 feat(navigation): added nav icon padding
  src/plugins/navigation/style.css
Labels: bug

#2903 fix(discord-plugin): handle album name padding if length < 2
  src/plugins/discord/main.ts
Labels: bug
