Repository th-ch/youtube-music, pull requests merged in 2025-06, with the labels that each got.

#3424 Improve README-es.md by adjusting the bad Spanish translation
  docs/readme/README-es.md
Labels: documentation

#3366 fix: use gtk 3 switch as workaround
  src/index.ts
Labels: bug, electron-issue

#3440 feat(api-server): add optional params for search
  src/plugins/api-server/backend/routes/control.ts
  src/plugins/api-server/backend/scheme/search.ts
  src/providers/song-controls.ts
  src/renderer.ts
Labels: enhancement
