Repository th-ch/youtube-music, pull requests merged in 2025-07, with the labels that each got.

#3162 perf(synced-lyrics): virtual scrolling
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/plugins/downloader/main/index.ts
  src/plugins/synced-lyrics/renderer/components/LyricsContainer.tsx
  src/plugins/synced-lyrics/renderer/components/LyricsPicker.tsx
  src/plugins/synced-lyrics/renderer/components/NotFoundKaomoji.tsx
  src/plugins/synced-lyrics/renderer/components/PlainLyrics.tsx
  src/plugins/synced-lyrics/renderer/components/SyncedLine.tsx
  src/plugins/synced-lyrics/renderer/components/index.ts
  src/plugins/synced-lyrics/renderer/index.ts
  src/plugins/synced-lyrics/renderer/renderer.tsx
  src/plugins/synced-lyrics/renderer/utils.tsx
  src/plugins/synced-lyrics/style.css
  tsconfig.json
Labels: enhancement

#3502 feat: enable rolldown native plugin
  electron.vite.config.mts
  vite-plugins/plugin-loader.mts
Labels: enhancement

#3551 fix(discord): Presence reacts to pause/play
  src/plugins/discord/discord-service.ts
Labels: bug

#3582 docs: add Unobtrusive Player in available plugins
  README.md
Labels: documentation

#3593 feat: code splitting
  src/config/plugins.ts
  src/i18n/index.ts
  src/index.ts
  src/loader/main.ts
  src/loader/menu.ts
  src/loader/preload.ts
  src/loader/renderer.ts
  src/menu.ts
  src/plugins/precise-volume/renderer.ts
  src/plugins/shortcuts/mpris.ts
  src/plugins/video-toggle/index.tsx
  src/preload.ts
  src/virtual-module.d.ts
  vite-plugins/i18n-importer.mts
  vite-plugins/plugin-importer.mts
Labels: enhancement

#3667 Fixed: Outdated querySelector
  src/plugins/skip-disliked-songs/index.ts
Labels: bug

#3627 fix(api-server): Fixes the duplicated clientId saved in authorizedClients
  src/plugins/api-server/backend/routes/auth.ts
Labels: enhancement
