Repository th-ch/youtube-music, pull requests merged in 2025-03, with the labels that each got.

#3047 fix: added French link in general README file
  README.md
  docs/readme/README-es.md
  docs/readme/README-fr.md
  docs/readme/README-hu.md
  docs/readme/README-is.md
  docs/readme/README-ko.md
  docs/readme/README-ru.md
Labels: documentation

#3093 feat: Allow scrobbling using alternative song titles
  src/i18n/resources/en.json
  src/plugins/scrobbler/index.ts
  src/plugins/scrobbler/menu.ts
  src/plugins/scrobbler/services/lastfm.ts
  src/plugins/scrobbler/services/listenbrainz.ts
  src/providers/song-info.ts
Labels: enhancement

#3091 Update winget-releaser version to main
  .github/workflows/winget-submission.yml
Labels: bug

#3104 feat(plugin): add unobtrusive player plugin
  src/i18n/resources/en.json
  src/plugins/unobtrusive-player/index.ts
  src/plugins/unobtrusive-player/style.css
Labels: enhancement

#2790 feat(synced-lyrics): romanization
  electron.vite.config.mts
  package.json
  patches/@malept__flatpak-bundler@0.4.0.patch
  patches/eslint-plugin-import@2.29.1.patch
  patches/kuromoji@0.1.2.patch
  pnpm-lock.yaml
  src/i18n/resources/en.json
  src/index.ts
  src/plugins/synced-lyrics/index.ts
  src/plugins/synced-lyrics/menu.ts
  src/plugins/synced-lyrics/providers/LyricsGenius.ts
  src/plugins/synced-lyrics/renderer/components/LyricsContainer.tsx
  src/plugins/synced-lyrics/renderer/components/PlainLyrics.tsx
  src/plugins/synced-lyrics/renderer/components/SyncedLine.tsx
  src/plugins/synced-lyrics/renderer/utils.tsx
  src/plugins/synced-lyrics/style.css
  src/plugins/synced-lyrics/types.ts
  src/ts-declarations/kuroshiro-analyzer-kuromoji.d.ts
  src/ts-declarations/kuroshiro.d.ts
Labels: enhancement

#3158 fix(README): Fixed typos in some hyperlinks
  README.md
  docs/readme/README-es.md
  docs/readme/README-fr.md
  docs/readme/README-hu.md
  docs/readme/README-is.md
  docs/readme/README-ko.md
  docs/readme/README-ru.md
Labels: documentation
